language: scala
scala:
   - 2.12.1
jdk:
  - oraclejdk8
before_script:
  # pull down gwen source dependency
  - cd ..
  - git clone https://github.com/gwen-interpreter/gwen.git
  - cd gwen-web
  # use virtual frame buffers to run browser tests
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
add_ons:
  - firefox: "50.1.0"
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.13.0/geckodriver-v0.13.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.13.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver